### ISSUE TITLE
Facing issues in chaincode while changing 0.6 fabric version to 1.0 

### ISSUE THREAD

**Issue by harinishree** [IBM-Blockchain-Archive/learn-chaincode#203]
we used 0.6  fabric version to build the chaincode now i am trying to change the cahincode to 1.0 fabric version I done  with my setup at 1.0 version  at that time i am facing this error ./digital.go:288: cannot use new(SimpleChaincode) (type *SimpleChaincode) as type shim.Chaincode in argument to shim.Start:
	*SimpleChaincode does not implement shim.Chaincode (wrong type for Init method)
		have Init(shim.ChaincodeStubInterface, string, []string) ([]byte, error)
		want Init(shim.ChaincodeStubInterface) peer.Response

please anyone help me to solve this issue

Thanks in advance

**Comment by mrshah-at-ibm** [comment]
@harinishree this repository has been archived and there are no updates and help.

Looks like your chaincode is not up-to-date on the shim. Please refer to the latest chaincode examples for help.

**Comment by harinishree** [comment]
Sir I updated my shim package in my chaincode again i am facing this  same  issue can u plz give a solution for this

**Comment by mrshah-at-ibm** [comment]
Hi @harinishree please refer to https://github.com/IBM-Blockchain/marbles as an example for v1.x fabric.

**Comment by harinishree** [comment]
Sir I am having one doubt regarding chaincode I wrote one function in my chaincode using go lang  I started running  chaincode using terminal but I need to check console (fmt.println)  I want to know my console what I mentioned in my function I dont have any idea regarding this where I need to check console pls give me a solution for this 

Thanks in advance

**Comment by mrshah-at-ibm** [comment]
look at your chaincode container logs.
